# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_weight',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
