# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0003_auto_20171211_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_sex',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
