# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0004_auto_20171212_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_personality',
            new_name='personality',
        ),
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_weight',
            new_name='weight',
        ),
    ]
