# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0005_auto_20171212_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='pattern',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
