# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0009_auto_20171218_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingdogreport',
            name='label',
        ),
        migrations.AddField(
            model_name='missingdogreport',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 12, 19, 18, 39, 9, 280214, tzinfo=utc)),
        ),
    ]
