# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0010_auto_20171219_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingdogreport',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2017, 12, 19, 18, 43, 23, 654835, tzinfo=utc)),
        ),
    ]
