# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0014_auto_20171219_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingdogreport',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
