# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0015_auto_20171219_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingdogreport',
            name='timestamp',
            field=models.DateTimeField(auto_created=django.utils.timezone.now),
        ),
    ]
