# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0017_auto_20171221_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='missing_since',
            field=models.DateTimeField(default=None),
        ),
    ]
