# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggonnitapp', '0018_auto_20171229_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='missing_since',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
